import Head from "next/head";
import { Header } from "@/components/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Thiago Calazans - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>

      {/* <motion.div
        className="w-96 h-96 rounded-md bg-brand-primary"
        animate={{
          scale: [1, 1],
          rotate: [0, 5],
        }}
        transition={{
          duration: 2,
          ease: "easeInOut",
          times: [0, 0.2, 0.5, 0.8, 1],
          repeatDelay: 1,
        }}
      /> */}
    </>
  );
}
